### ISSUE TITLE
    hi! i run you project turn error. 

### ISSUE THREAD

**Issue by zlwzlwzlw** [weizhenzhao/TextCNN_Tensorflow_Serving#1]

**Comment by zlwzlwzlw** [comment]
result = stub.Predict(request, 60.0)  # 10 secs timeout   File "/opt/anaconda3/lib/python3.6/site-packages/grpc/_channel.py", line 533, in __call__     return _end_unary_response_blocking(state, call, False, None)   File "/opt/anaconda3/lib/python3.6/site-packages/grpc/_channel.py", line 467, in _end_unary_response_blocking     raise _Rendezvous(state, None, None, deadline) grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with: 	status = StatusCode.NOT_FOUND 	details = "Servable not found for request: Latest(text_classified_model)" 	debug_error_string = "{"created":"@1554368809.038624811","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1017,"grpc_message":"Servable not found for request: Latest(text_classified_model)","grpc_status":5}"

**Comment by weizhenzhao** [comment]
can you take a snapshot?

thanks
weizhen

**Comment by zlwzlwzlw** [comment]
![image](https://user-images.githubusercontent.com/33961256/55711004-6dd97f80-5a1e-11e9-89cd-61884a87731e.png)
i only change the server ip and iport 8500
thanks

**Comment by zlwzlwzlw** [comment]
its ok ,thankyou!
